package com.hindi.vargpaheli.model

import android.content.Context
import org.json.JSONArray

/** Loads the 100 offline puzzles from assets/puzzles.json (generated by tools/gen_puzzles.py). */
object PuzzleRepository {
    private var cache: List<Puzzle>? = null

    fun all(context: Context): List<Puzzle> = cache ?: load(context).also { cache = it }

    fun get(context: Context, id: Int): Puzzle = all(context).first { it.id == id }

    private fun load(context: Context): List<Puzzle> {
        val text = context.assets.open("puzzles.json").bufferedReader().use { it.readText() }
        val arr = JSONArray(text)
        return List(arr.length()) { i ->
            val p = arr.getJSONObject(i)
            val g = p.getJSONArray("grid")
            val grid = List(g.length()) { r ->
                val row = g.getJSONArray(r)
                List(row.length()) { c -> row.getString(c).ifEmpty { null } }
            }
            val cl = p.getJSONArray("clues")
            val entries = List(cl.length()) { k ->
                val o = cl.getJSONObject(k)
                Puzzle.Entry(o.getInt("r"), o.getInt("c"), o.getString("d") == "A", o.getString("ans"), o.getString("clue"))
            }
            Puzzle.build(p.getInt("id"), p.getString("title"), grid, entries)
        }
    }
}
